# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=200)),
                ('client_id', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_id', models.CharField(max_length=30, null=True, unique=True)),
                ('policy_id', models.IntegerField(null=True)),
                ('pan_id', models.CharField(max_length=30, null=True)),
                ('aadhar_id', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('phone_no', models.CharField(max_length=30, null=True)),
                ('fraud_desc', models.CharField(max_length=30, null=True)),
                ('block_status', models.IntegerField(null=True)),
                ('notification_status', models.IntegerField(null=True)),
                ('fraud_date', models.DateField(null=True)),
                ('fraud_identified_date', models.DateField(null=True)),
                ('fraud_notified_date', models.DateField(null=True)),
                ('fraud_reported_to_block', models.IntegerField(null=True)),
                ('fraud_reported_to_block_date', models.DateField(null=True)),
                ('fraud_type', models.CharField(max_length=30, null=True)),
                ('fraud_status', models.CharField(blank=True, max_length=30, null=True)),
                ('claim_no', models.CharField(max_length=30, null=True)),
                ('vch_account_no', models.CharField(max_length=30, null=True)),
                ('vch_beneficiary_name', models.CharField(max_length=30, null=True)),
                ('vch_bank_name', models.CharField(max_length=30, null=True)),
                ('vch_FS_code', models.CharField(max_length=30, null=True)),
                ('vch_account_type', models.CharField(max_length=30, null=True)),
                ('c_type', models.CharField(max_length=30, null=True)),
                ('engine_number', models.CharField(max_length=30, null=True)),
                ('chasis_no', models.CharField(max_length=30, null=True)),
                ('registration_no', models.CharField(max_length=30, null=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ClientDetail')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=70, null=True)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('account_validity', models.DateField()),
                ('user_type', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super_Admin')], default='ADMIN', max_length=30)),
                ('insurence_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ClientDetail')),
            ],
        ),
    ]
