# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_auto_20180906_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminfraud',
            name='fraud_identified_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adminfraud',
            name='fraud_notified_date',
            field=models.DateField(null=True),
        ),
    ]
