# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20180907_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminfraud',
            name='fraud_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
