# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspicious_Cases',
            fields=[
                ('Claim_No', models.IntegerField(max_length=60, primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=30)),
                ('Card_No', models.IntegerField(max_length=15)),
                ('Policy_no', models.CharField(max_length=37)),
                ('Policy_from', models.DateTimeField()),
                ('Sum_Insured', models.IntegerField(max_length=50)),
                ('Group_Name', models.CharField(max_length=60)),
                ('NSP_City', models.CharField(max_length=45)),
            ],
        ),
    ]
